# This file is all the variables needed by terraform to set up the cluster infra.

cloud:
    name: alaska # name in clouds.yaml

cluster:
    name: p4
    keyfile: "~/.ssh/id_rsa.pub" # NB must have a matching private keyfile w/o .pub extension
    user: centos
    groups: ["login", "compute"] # TODO: change this to a dict
    login:
        name: "login"
        flavor: "general.v1.medium" # VM
        num_nodes: 1
        networks:
            - "ilab"
        image: "CentOS7.8-OpenHPC"
        config_drive: false
    compute:
        name: "batch"
        flavor: "compute-A"
        resource_class: "COMPUTE_A" # only defined if baremetal - could use this fact?
        num_nodes: 2
        networks:
            - "ilab"
            - "p3-bdn"
            - "p3-lln"
        image: "CentOS7.8-OpenHPC"
        config_drive: true

    roles:
    - name: "ceph_client"
      groups: ["login", "compute"]
    - name: "latest_packages"
      groups: ["login", "compute"]
    - name: "login"
      groups: ["login"]
    - name: "control"
      groups: ["login"]
    - name: "batch"
      groups: ["compute"]
    - name: "runtime"
      groups: ["login", "compute"]
    - name: "mdadm"
      groups: ["compute"]
    - name: "beegfs_mgmt"
      groups: ["login"]
    - name: "beegfs_mds"
      groups: ["login"]
    - name: "beegfs_oss"
      groups: ["compute"]
    - name: "beegfs_client"
      groups: ["login", "compute"]
    - name: "nfs_server"
      groups: ["login"]
    - name: "nfs_client"
      groups: ["compute"]

