# Deploy the slurm-driven rebuild script + dependencies.
# See top-level README for usage.
#
# NB: assumes an access credential has been added to e.g. /etc/openstack - done using terraform here.

- hosts:
  - cluster_batch
  gather_facts: false
  become: true
  tasks:
    - name: install python3
      yum:
        name: python3
    - name: install slurm-openstack-tools
      pip:
        virtualenv: /opt/slurm-tools
        name: git+https://github.com/stackhpc/slurm-openstack-tools.git
        virtualenv_python: python3
    - name: add RebootProgram to slurm.conf
      lineinfile:
        path: "{{ openhpc_slurm_conf.location }}"
        regexp: "^RebootProgram=.*$"
        line: "RebootProgram=/opt/slurm-tools/bin/slurm-openstack-rebuild"
      register: slurm_conf
      run_once: "{{ openhpc_slurm_conf.shared_fs }}"
    - name: reconfigure slurm
      shell:
        cmd: "scontrol reconfigure"
      when: slurm_conf.changed
      run_once: true

# for py2:
# sudo yum install python3
# sudo yum install python-virtualenv
# virtualenv --python=python3 venv
# . venv/bin/activate
# pip install -U pip
# pip install "openstacksdk<=0.39" # for py2
# pip install "python-openstackclient<=4.0.0" # for py2
# pip install "subprocess32>=3.5.0" # for py2

