# Deploy the slurm-driven rebuild script + dependencies.
# See reboot.py for usage.
#
# NB: assumes an access credential has been added to e.g. /etc/openstack - done using terraform here.

- hosts:
  - cluster_login
  - cluster_control
  - cluster_batch
  - cluster_runtime
  gather_facts: false
  become: true
  tasks:
    - name: add RebootProgram to slurm.conf
      lineinfile:
        path: "{{ openhpc_slurm_conf.location }}"
        regexp: "^RebootProgram=.*$"
        line: "RebootProgram={{ alaska_homedir }}/slurm/reboot.py" # TODO fix assumptions/name re. shared directory here?
      run_once: "{{ openhpc_slurm_conf.shared_fs }}"
      register: slurm_conf
    - name: reconfigure slurm
      shell:
        cmd: "scontrol reconfigure" # TODO: remove env var
      when: slurm_conf.changed
      run_once: true

- hosts: cluster_batch
  gather_facts: false
  become: true
  tasks:
    - name: deploy RebootProgram
      copy:
        src: ../reboot.py
        dest: "{{ alaska_homedir }}/slurm/reboot.py" # TODO fix assumptions/name re. shared directory here?
        mode: u+x
      run_once: "{{ openhpc_slurm_conf.shared_fs }}"
    - name: install python3
      yum:
        name:
          - python3
          - python3-pip
    - name: install openstacksdk
      command: pip3 install openstacksdk # TODO: pin version TODO: use virtualenv TODO: changed_when


# for py2:
# sudo yum install python3
# sudo yum install python-virtualenv
# virtualenv --python=python3 venv
# . venv/bin/activate
# pip install -U pip
# pip install "openstacksdk<=0.39" # for py2
# pip install "python-openstackclient<=4.0.0" # for py2
# pip install "subprocess32>=3.5.0" # for py2

